### ISSUE TITLE
snmpdf.c - Which type use to print hrStorageFixedDisk

### ISSUE THREAD

**Issue by Isma399** [travelping/net-snmp#1]
Hello,

I'm trying to modify this one (snmpdf.c) to have only disks printed (with type hrStorageFixedDisk), like what is said line 242.
For the beginning, I just want to print the OID hrStorageFixedDisk
Add that : 
`char             hstype[MAX_OID_LEN];`  
`add(pdu, "HOST-RESOURCES-MIB:hrStorageType", &(vlp->name[base_length]), vlp->name_length - base_length);`
and: 
`vlp2 = vlp2->next_variable;
            memcpy(hstype, vlp2->val.objid, vlp2->val_len/sizeof(oid));
            hstype[vlp2->val_len] = '\0';
            printf("\thstype : %s\n",hstype);`

Compiling is OK but it returns nothing. I've tried different type char, oid but I didn't manage to find the good one.
Debugging the script shows the returned OID : 

> trace: snmp_parse_var_op(): snmp.c, 164:
> dumph_recv:         Name
> dumpx_recv:          06 0B 2B 06 01 02 01 19 02 03 01 02 3D
> dumpv_recv:            ObjID: HOST-RESOURCES-MIB::hrStorageType.61
> trace: snmp_pdu_parse(): snmp_api.c, 4512:
> dumph_recv:         Value
> dumpx_recv:          06 09 2B 06 01 02 01 19 02 01 04
> dumpv_recv:            **ObjID: HOST-RESOURCES-TYPES::hrStorageFixedDisk**
> trace: _sess_process_packet(): snmp_api.c, 5244:

**Comment by Isma399** [comment]
I manage to print all the answer, but I just want the value, not the OID : 

`print_variable(vlp2->name, vlp2->name_length, vlp2);`

> HOST-RESOURCES-MIB::hrStorageType.61 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk

**Comment by Isma399** [comment]
Ok, I've just found print_value in /usr/include/net-snmp/varbind_api.h . 
Sorry.

> OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk

I want now to have the value stored in a variable : 
`char             hstype[MAX_OID_LEN];`
`vlp2 = vlp2->next_variable;`
`memcpy(hstype, vlp2->name , vlp2->name_length);`
`printf(hstype);`
Nothing is returned

**Comment by hsychla** [comment]
Hello @Isma399 , 

we are not the original author of net-snmp, we only added functionality we needed.

For questions regarding the implementation please contact the original project as described on http://www.net-snmp.org/support/contacts.html

Best Regards

**Comment by Neustradamus** [comment]
@Isma399: The official project is on GitHub:
- https://github.com/net-snmp/net-snmp
- https://github.com/net-snmp
